### ISSUE TITLE
Need to update documentation 

### ISSUE THREAD

**Issue by onimsha** [christiangda/puppet-powerdns#1]
In example of

``` ruby
class { '::powerdns::backend':  
  backend_name => 'pgsql',  
  ensure       => true,  
```

ensure is bool type, however in [https://github.com/christiangda/puppet-powerdns/blob/master/manifests/backend.pp#L15](url), this variable is compared with a array of strings.

``` ruby
  if ! ($ensure in [ 'present', 'installed', 'absent', 'purged', 'held', 'latest' ]) {
    fail("\"${::status}\" is not a valid status parameter value")
  }
```

We need to update the Readme for reflecting this usage.

**Comment by christiangda** [comment]
Hi Alex, Thanks, Iill fix this.

**Comment by christiangda** [comment]
Fixed, thanks onimsha
