### ISSUE TITLE
Parameter usage in ::powerdns::backend

### ISSUE THREAD

**Issue by onimsha** [christiangda/puppet-powerdns#3]
In [https://github.com/christiangda/puppet-powerdns/blob/master/manifests/backend.pp#L26](url) , we have following parameter:

``` ruby
$config_options = $::powerdns::params::config_options
```

However in `params.pp`, it doesn't define any `config_options` parameter. Instead, there is a hash named `default_config`, which i'm assuming that it is providing what `$config_options` supposed to do. 

I think it should be 

``` ruby
 $config_options = $::powerdns::params::default_config
```

**Comment by christiangda** [comment]
Hi Onimsha,  thank you for your collaboration.  I fixed it, in master branch
