### ISSUE TITLE
Apache License Violation

### ISSUE THREAD

**Issue by jmkeyes** [christiangda/puppet-powerdns#7]
It appears that some small parts of this module's code have been lifted directly from the PowerDNS module I've published to Github and the Puppet Forge.

The module I've published is licensed under the Apache 2.0 license which forbids the removal and/or alteration of copyright/license notices.

I'd appreciate it if you could restore the original copyright notice(s) and provide some attribution for the code you've used.

Source(s): 

From `spec/spec_helper.rb`:
* [`jmkeyes/powerdns` "Initial Commit" - May 27, 2015 - df6b980e](https://github.com/jmkeyes/puppet-powerdns/blob/df6b980eb08abfbf8bb197c74ddf49b1a808246c/spec/spec_helper.rb)
* [`christiangda/powerdns` - "improved: added a lot..." - Jan 6, 2016 - b83de722](https://github.com/christiangda/puppet-powerdns/blob/b83de7229f953d550fdceb17a9a3d37a8bdbdb50/spec/spec_helper.rb)

From: `spec/defines/setting_spec.rb`:
* [`jmkeyes/powerdns` "Initial Commit" - May 27, 2015 - df6b980e](https://github.com/jmkeyes/puppet-powerdns/blob/df6b980eb08abfbf8bb197c74ddf49b1a808246c/spec/defines/setting_spec.rb)
* [`christiangda/powerdns` - "improved: added a lot..." - Jan 6, 2016 - b83de722](https://github.com/christiangda/puppet-powerdns/blob/b83de7229f953d550fdceb17a9a3d37a8bdbdb50/spec/defines/setting_spec.rb)

From `manifests/init.pp`:
* [`jmkeyes/powerdns` "Initial Commit" - May 29, 2015 - df6b980](https://github.com/jmkeyes/puppet-powerdns/blob/df6b980eb08abfbf8bb197c74ddf49b1a808246c/manifests/init.pp#L21-L24)
* [`christiangda/puppet-powerdns` - "added first functionality: install package" - Jan 5th, 2016 - 15b7e92](https://github.com/christiangda/puppet-powerdns/blob/15b7e920da037d6494cc58898ab0b7a2a54eb388/manifests/init.pp#L44-L47)

Thank you!

**Comment by christiangda** [comment]
Hi @jmkeyes , thank you for your advice,  but I don't copy any of your code, I don't understand  why yo do that?, this is Open Source Software!,  I apreciated that you had time to look on all my code!, but instead of looking similitude between your module and my module, use this and you will report a really bug.
